# Default values for studentai.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  replicaCount: 1
  image:
    repository: 975050024946.dkr.ecr.ap-south-1.amazonaws.com/studentai-backend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

frontend:
  replicaCount: 1
  image:
    repository: 975050024946.dkr.ecr.ap-south-1.amazonaws.com/studentai-frontend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 3000
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: "TODO: studentai.local"
        paths:
          - path: /
            pathType: ImplementationSpecific
  env:
    VITE_API_BASE_URL: "http://studentai-backend:8080"

monitoring:
  enabled: false
  scrapeInterval: 15s

serviceAccount:
  create: true
  annotations: {}
  name: ""
  automount: true
